"""Trigger types."""

from enum import Enum


class TriggerType(Enum):
    """Trigger types."""

    GENERIC = 1
    IMMEDIATE = 2
    IMMEDIATE_SENSOR_FUSION = 3
    KILLED_AGENTS_AT_POSITION = 4
    AGENT_AT_POSITION = 5
    AGENT_IN_AREA = 6
    AGENT_NOT_IN_AREA = 7
    AGENT_CROSSED_BOUNDARY = 8
    AGENT_MOVED_OUT_OF_AREA = 9
    TIME = 10
    COMPOUND_AND = 11
    COMPOUND_OR = 12
    ALIVE_AGENTS_AT_POSITION = 13
    AGENT_KILLED = 14
    AGENT_FIRED_WEAPON = 15
    WEAPON_FIRED_NEAR_LOCATION = 16
    WEAPON_FIRED_NEAR_AGENT = 17
    AGENTS_SENSED = 18
    AGENTS_SENSED_IN_RANGE = 19
    MISSION_MESSAGE = 20
    ILLUMINATED_BY_SENSOR = 21
